# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iviLZ4y_c-pNsYCEEIKzmfTzC50umtCS
"""

import streamlit as st
from transformers import pipeline
from deep_translator import GoogleTranslator
import os
import requests
from PIL import Image
import io

st.set_page_config(
    page_title="Beyond Emotions",
    page_icon="🎨",
    layout="wide"
)

if "started" not in st.session_state:
    st.session_state.started = False

if not st.session_state.started:

    st.markdown("""
    <style>
    .stApp { background-color: #f6f1ea; }

    .main-title {
        text-align: center;
        font-size: 52px;
        font-family: Georgia, serif;
        font-weight: bold;
        color: #111;
        margin-top: 20px;
        margin-bottom: 8px;
    }

    .subtitle {
        text-align: center;
        color: #666;
        font-size: 16px;
        margin-bottom: 30px;
    }

    .card-title {
        text-align: center;
        font-size: 15px;
        font-weight: bold;
        padding-top: 8px;
        color: #111;
    }

    .card-artist {
        text-align: center;
        font-size: 12px;
        color: #777;
        padding-bottom: 10px;
    }

    .stButton > button {
        background-color: #c9983d !important;
        color: white !important;
        border-radius: 30px !important;
        border: none !important;
        font-size: 18px !important;
        font-weight: bold !important;
        padding: 12px 24px !important;
    }
    </style>
    """, unsafe_allow_html=True)

    st.markdown(
        '<div class="main-title">🎨 Famous Paintings of the World</div>',
        unsafe_allow_html=True
    )

    st.markdown(
        '<div class="subtitle">A curated collection of the most celebrated masterpieces throughout history.</div>',
        unsafe_allow_html=True
    )

    paintings = [
        ("Mona Lisa", "Leonardo da Vinci", "https://upload.wikimedia.org/wikipedia/commons/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg"),
        ("The Scream", "Edvard Munch", "https://upload.wikimedia.org/wikipedia/commons/f/f4/The_Scream.jpg"),
        ("Girl with a Pearl Earring", "Johannes Vermeer", "https://upload.wikimedia.org/wikipedia/commons/d/d7/Meisje_met_de_parel.jpg"),
        ("The Persistence of Memory", "Salvador Dalí", "https://upload.wikimedia.org/wikipedia/en/d/dd/The_Persistence_of_Memory.jpg"),
    ]

    cols = st.columns([1, 1, 1, 1], gap="large")

    for col, (name, artist, img) in zip(cols, paintings):
        with col:
            st.image(img, use_container_width=True)
            st.markdown(f"<div class='card-title'>{name}</div>", unsafe_allow_html=True)
            st.markdown(f"<div class='card-artist'>{artist}</div>", unsafe_allow_html=True)

    st.markdown("<br><br>", unsafe_allow_html=True)

    col1, col2, col3 = st.columns([3, 1, 3])

    with col2:
        if st.button("✨ Explore More", use_container_width=True):
            st.session_state.started = True
            st.rerun()

else:

    st.markdown("""
    <style>
    .stApp { background-color: #f6f1ea; }

    .title {
        text-align: center;
        font-size: 48px;
        font-family: Georgia, serif;
        font-weight: bold;
        color: #111;
    }

    .subtitle2 {
        text-align: center;
        color: #666;
        font-size: 18px;
        margin-bottom: 30px;
        font-style: italic;
    }

    .stButton > button {
        background-color: #c9983d !important;
        color: white !important;
        border-radius: 30px !important;
        border: none !important;
        font-size: 18px !important;
        font-weight: bold !important;
    }

    .result-card {
        background: white;
        padding: 20px;
        border-radius: 16px;
        margin-top: 20px;
        box-shadow: 0 4px 14px rgba(0,0,0,0.10);
    }

    .prompt-box {
        background: #fff8ea;
        padding: 16px;
        border-radius: 14px;
        margin-top: 15px;
        border-left: 5px solid #c9983d;
    }
    </style>
    """, unsafe_allow_html=True)

    if st.button("⬅️ Back to Gallery"):
        st.session_state.started = False
        st.rerun()

    st.markdown('<div class="title">🎨 Beyond Emotions</div>', unsafe_allow_html=True)

    st.markdown(
        '<div class="subtitle2">Transform your feelings into AI-generated emotional artwork.</div>',
        unsafe_allow_html=True
    )

    @st.cache_resource
    def load_emotion():
        return pipeline(
            "text-classification",
            model="nadanejmat/beyond-emotions-model",
            tokenizer="nadanejmat/beyond-emotions-model",
            device=-1
        )

    HF_TOKEN = os.environ.get("HF_TOKEN")
    API_URL = "https://api-inference.huggingface.co/models/runwayml/stable-diffusion-v1-5"

    def generate_image_api(prompt):

        if not HF_TOKEN:
            st.error("HF_TOKEN is missing. Please add it in Render Environment Variables.")
            return None

        headers = {
            "Authorization": f"Bearer {HF_TOKEN}"
        }

        payload = {
            "inputs": prompt,
            "options": {
                "wait_for_model": True
            }
        }

        try:
            response = requests.post(
                API_URL,
                headers=headers,
                json=payload,
                timeout=300
            )

            if response.status_code != 200:
                st.error("Image generation API error:")
                st.write(response.text)
                return None

            content_type = response.headers.get("content-type", "")

            if "image" not in content_type:
                st.error("The API did not return an image.")
                st.write(response.text)
                return None

            image = Image.open(io.BytesIO(response.content))
            return image

        except requests.exceptions.Timeout:
            st.error("Image generation took too long. Please try again.")
            return None

        except Exception as e:
            st.error(f"Unexpected error: {e}")
            return None

    def is_arabic(text):
        arabic_chars = sum(1 for c in text if '\u0600' <= c <= '\u06FF')
        return len(text) > 0 and arabic_chars / len(text) > 0.3

    def translate_to_english(text):
        try:
            return GoogleTranslator(source="auto", target="en").translate(text)
        except Exception:
            return text

    def normalize_emotion(emotion):
        mapping = {
            "sadness": "sadness",
            "joy": "joy",
            "anger": "anger",
            "fear": "fear",
            "love": "love",
            "surprise": "awe"
        }
        return mapping.get(emotion.lower(), "something_else")

    def direct_emotion_input(text):
        text = text.lower().strip()

        direct_map = {
            "sad": "sadness",
            "sadness": "sadness",
            "happy": "joy",
            "joy": "joy",
            "angry": "anger",
            "anger": "anger",
            "fear": "fear",
            "afraid": "fear",
            "love": "love",
            "surprise": "awe",
            "surprised": "awe",
            "awe": "awe",
            "funny": "amusement",
            "amusement": "amusement",
            "laugh": "amusement",
            "regret": "regret",
            "remorse": "regret",
            "guilty": "regret"
        }

        return direct_map.get(text, None)

    def emotion_to_prompt(emotion):
        prompts = {
            "joy": "a magical sunrise over flower fields, glowing golden light, dreamy fantasy atmosphere, cinematic art, highly detailed, 4k",
            "sadness": "a lonely figure standing in rain at night, blue cinematic tones, emotional digital painting, highly detailed, 4k",
            "anger": "a warrior surrounded by fire and smoke, intense dramatic lighting, chaotic atmosphere, cinematic digital art, 4k",
            "fear": "a dark haunted forest with glowing eyes between trees, horror atmosphere, cinematic lighting, highly detailed, 4k",
            "love": "two souls meeting under glowing stars, romantic fantasy atmosphere, soft golden lighting, highly detailed, 4k",
            "awe": "a giant glowing galaxy above snowy mountains, breathtaking fantasy landscape, cinematic atmosphere, 4k",
            "amusement": "a playful colorful carnival at night, glowing lights, cheerful mood, whimsical digital illustration, 4k",
            "regret": "a person sitting alone beside old letters, faded colors, nostalgic atmosphere, cinematic emotional painting, 4k",
            "something_else": "abstract emotional energy waves, surreal colors, dreamlike artistic atmosphere, modern digital art, 4k"
        }

        return prompts.get(emotion, prompts["something_else"])

    text = st.text_area(
        "Enter your feeling (Arabic or English):",
        height=150
    )

    art_style = st.selectbox(
        "Choose Art Style:",
        [
            "Digital Art",
            "Oil Painting",
            "Watercolor",
            "Fantasy Art",
            "Cinematic",
            "Surrealism"
        ]
    )

    if st.button("🎨 Generate Artwork"):

        if text.strip():

            with st.spinner("Analyzing emotion..."):

                emotion_model = load_emotion()

                if is_arabic(text):
                    processed_text = translate_to_english(text)
                else:
                    processed_text = text

                direct_emotion = direct_emotion_input(processed_text)

                if direct_emotion:
                    raw_emotion = direct_emotion
                    emotion = direct_emotion
                    confidence = 1.0
                else:
                    result = emotion_model(processed_text)[0]
                    raw_emotion = result["label"]
                    emotion = normalize_emotion(raw_emotion)
                    confidence = result["score"]

                prompt = emotion_to_prompt(emotion)
                prompt = prompt + f", {art_style} style"

            st.markdown('<div class="result-card">', unsafe_allow_html=True)
            st.write("Original Text:", text)
            st.write("Translated / Processed Text:", processed_text)
            st.write("Detected Emotion:", raw_emotion)
            st.write("Final Emotion:", emotion)
            st.write("Confidence:", round(confidence * 100, 2), "%")
            st.progress(float(confidence))
            st.markdown("</div>", unsafe_allow_html=True)

            st.markdown('<div class="prompt-box">', unsafe_allow_html=True)
            st.write("Generated Prompt:")
            st.write(prompt)
            st.markdown("</div>", unsafe_allow_html=True)

            with st.spinner("Generating artwork... this may take up to 1 minute"):
                image = generate_image_api(prompt)

            if image is not None:

                col1, col2, col3 = st.columns([1, 1.6, 1])

                with col2:
                    st.image(
                        image,
                        caption="AI-generated emotional artwork",
                        use_container_width=True
                    )

                    img_bytes = io.BytesIO()
                    image.save(img_bytes, format="PNG")

                    st.download_button(
                        label="💾 Download Artwork",
                        data=img_bytes.getvalue(),
                        file_name="beyond_emotions_art.png",
                        mime="image/png"
                    )

        else:
            st.warning("Please write something first.")
