# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iviLZ4y_c-pNsYCEEIKzmfTzC50umtCS
"""

import streamlit as st
from transformers import pipeline
from deep_translator import GoogleTranslator
import torch
import random
import io

st.set_page_config(
    page_title="Beyond Emotions",
    page_icon="🎨",
    layout="wide"
)

if "started" not in st.session_state:
    st.session_state.started = False

if not st.session_state.started:

    st.markdown("""
    <style>

    .stApp {
        background-color: #f6f1ea;
    }

    .main-title {
        text-align: center;
        font-size: 52px;
        font-family: Georgia, serif;
        font-weight: bold;
        color: #111;
        margin-top: 20px;
        margin-bottom: 8px;
    }

    .subtitle {
        text-align: center;
        color: #666;
        font-size: 16px;
        margin-bottom: 30px;
    }

    .card-title {
        text-align: center;
        font-size: 15px;
        font-weight: bold;
        padding-top: 8px;
        color: #111;
    }

    .card-artist {
        text-align: center;
        font-size: 12px;
        color: #777;
        padding-bottom: 10px;
    }

    .stButton > button {
        background-color: #c9983d !important;
        color: white !important;
        border-radius: 30px !important;
        border: none !important;
        font-size: 18px !important;
        font-weight: bold !important;
        padding: 12px 24px !important;
    }

    </style>
    """, unsafe_allow_html=True)

    st.markdown(
        '<div class="main-title">🎨 Famous Paintings of the World</div>',
        unsafe_allow_html=True
    )

    st.markdown(
        '<div class="subtitle">A curated collection of the most celebrated masterpieces throughout history.</div>',
        unsafe_allow_html=True
    )

    paintings = [
        ("Mona Lisa", "Leonardo da Vinci", "https://upload.wikimedia.org/wikipedia/commons/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg"),
        ("The Scream", "Edvard Munch", "https://upload.wikimedia.org/wikipedia/commons/f/f4/The_Scream.jpg"),
        ("Girl with a Pearl Earring", "Johannes Vermeer", "https://upload.wikimedia.org/wikipedia/commons/d/d7/Meisje_met_de_parel.jpg"),
        ("The Persistence of Memory", "Salvador Dalí", "https://upload.wikimedia.org/wikipedia/en/d/dd/The_Persistence_of_Memory.jpg"),
    ]

    cols = st.columns([1, 1, 1, 1], gap="large")

    for col, (name, artist, img) in zip(cols, paintings):

        with col:

            st.image(img, use_container_width=True)

            st.markdown(
                f"<div class='card-title'>{name}</div>",
                unsafe_allow_html=True
            )

            st.markdown(
                f"<div class='card-artist'>{artist}</div>",
                unsafe_allow_html=True
            )

    st.markdown("<br><br>", unsafe_allow_html=True)

    col1, col2, col3 = st.columns([3, 1, 3])

    with col2:

        if st.button("✨ Explore More", use_container_width=True):

            st.session_state.started = True

            st.rerun()

else:

    st.markdown("""
    <style>

    .stApp {
        background-color: #f6f1ea;
    }

    .title {
        text-align: center;
        font-size: 48px;
        font-family: Georgia, serif;
        font-weight: bold;
        color: #111;
    }

    .subtitle2 {
        text-align: center;
        color: #666;
        font-size: 18px;
        margin-bottom: 30px;
        font-style: italic;
    }

    .stButton > button {
        background-color: #c9983d !important;
        color: white !important;
        border-radius: 30px !important;
        border: none !important;
        font-size: 18px !important;
        font-weight: bold !important;
    }

    </style>
    """, unsafe_allow_html=True)

    if st.button("⬅️ Back to Gallery"):

        st.session_state.started = False

        st.rerun()

    st.markdown('<div class="title">🎨 Beyond Emotions</div>', unsafe_allow_html=True)

    st.markdown(
        '<div class="subtitle2">Transform your feelings into AI-generated emotional artwork.</div>',
        unsafe_allow_html=True
    )

    @st.cache_resource
    def load_emotion():

        return pipeline(
            "text-classification",
            model="nadanejmat/beyond-emotions-model",
tokenizer="nadanejmat/beyond-emotions-model",
            device=-1
        )


    def is_arabic(text):

        arabic_chars = sum(1 for c in text if '\u0600' <= c <= '\u06FF')

        return len(text) > 0 and arabic_chars / len(text) > 0.3

    def translate_to_english(text):

        try:
            return GoogleTranslator(
                source='auto',
                target='en'
            ).translate(text)

        except Exception:
            return text

    text = st.text_area(
        "Enter your feeling (Arabic or English):",
        height=150
    )

    if st.button("🎨 Generate Artwork"):

        if text.strip():

            with st.spinner("Analyzing emotion..."):
                
                emotion_model = load_emotion()
                
                if is_arabic(text):
                    processed_text = translate_to_english(text)
                else:
                    processed_text = text

                result = emotion_model(processed_text)[0]

                emotion = result["label"]

                confidence = result["score"]

            st.write("Detected Emotion:", emotion)

            st.write("Confidence:", round(confidence * 100, 2), "%")

        else:

            st.warning("Please write something first.")
